on: [push, pull_request]
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: pip install build
        - run: python -m build --sdist
        - uses: actions/upload-artifact@v3
          with:
            name: sdist
            path: dist/videojitter-*.tar.gz
            if-no-files-found: error
  pylint:
    runs-on: ubuntu-latest
    needs: build-sdist
    steps:
        - uses: actions/download-artifact@v3
          with:
            name: sdist
        - run: tar --gzip --extract --verbose --strip-components=1 --file videojitter-*.tar.gz
        - run: pip install --requirement pylint-requirements.txt --requirement requirements.txt
        # TODO: also pylint the test code
        - run: pylint src
